// Generated by CoffeeScript 1.3.3
(function() {
  "use strict";

  var _this = this;

  $(document).ready(function() {
    Logos.ReferenceTagging.lbsBibleVersion = "KJV";
    Logos.ReferenceTagging.lbsLinksOpenNewWindow = true;
    Logos.ReferenceTagging.lbsLogosLinkIcon = "dark";
    Logos.ReferenceTagging.lbsNoSearchTagNames = ["cite", "h1", "h2", "h3", "h4", "h5", "h6"];
    Logos.ReferenceTagging.lbsTargetSite = "biblia";
    Logos.ReferenceTagging.tag();
    Logos.ReferenceTagging.lbsCssOverride = true;
    $('.note').masonry({
      itemSelector: '.span6',
      columnWidth: 480
    });
  });

}).call(this);
